name: Elixir CI

on:
  pull_request:
    branches:
      - master

jobs:
  test:

    runs-on: ubuntu-18.04

    container:
      image: elixir:1.9.1-slim

    steps:
    - name: Checkout
      uses: actions/checkout@v1.0.0
    - name: build docker images
      run: |
        docker-compose build
    - name: run test
      run: |
        docker-compose run --rm umbrella mix ecto.reset
        docker-compose run --rm umbrella mix test
