name: Elixir CI

on:
  pull_request:
    branches: 
      - master

jobs:
  test:

    runs-on: ubuntu-18.04

    container:
      image: elixir:1.9.1-slim

    steps:
    - uses: actions/checkout@v1
    - name: Install Dependencies
      run: |
        mix local.rebar --force
        mix local.hex --force
        mix deps.get
    - name: Run Tests
      run: mix test
